
export const SET_NUMBER_CELL = 'SET_NUMBER_CELL'
export const SET_MESSAGE_NUMBER_CELL_INVALID = 'NUMBER_INVALID'
export const SET_MESSAGE_NUMBER_CELL_VALID = 'NUMBER_VALID'


export const INIT_BOARD = 'INIT_BOARD'
export const SET_VALUE_BOARD = 'SET_VALUE_BOARD'
export const CHANGE_TURN = 'CHANGE_TURN'
export const PLAYER_WIN = 'PLAYER_WIN'
